version: "3.7"
services:
  server:
    container_name: kube-server
    build:
      context: ./
      dockerfile: Dockerfile
    command: nodemon -r dotenv/config server.js
    depends_on:
      - mongodb
      - redis
      - dynamo
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "3000:3000"
  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    ports:
      - "27017:27017"
  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
  dynamo:
    container_name: dynamo
    image: amazon/dynamodb-local
    restart: always
    ports:
      - "8000:8000"

networks:
  default:
    name: kube-learning-network