apiVersion: v1
kind: Service
metadata:
  name: dynamo-service
spec:
  type: NodePort
  selector:
    run: dynamo
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30004
