apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  type: NodePort
  selector:
    run: server
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30001
