apiVersion: v1
kind: Pod
metadata:
  name: server
  labels:
    run: server
spec:
  containers:
  - name: server
    image: kubernetes-learning-server
    imagePullPolicy: Never
    ports:
    - containerPort: 3000
    env:
    - name: mongoDBEndpoint
      value: mongodb://mongo-service.default.svc.cluster.local:27017
    - name: redisEndpoint
      value: redis://redis-service.default.svc.cluster.local:6379
    - name: dynamodbEndpoint
      value: http://dynamo-service.default.svc.cluster.local:8000
    - name: AWS_ACCESS_KEY_ID
      value: test
    - name: AWS_SECRET_ACCESS_KEY
      value: test
    - name: AWS_REGION
      value: eu-central-1