apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  type: NodePort
  selector:
    run: mongo
  ports:
    - protocol: TCP
      port: 27120
      targetPort: 27017
      nodePort: 30002
