apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  type: NodePort
  selector:
    run: redis
  ports:
    - protocol: TCP
      port: 7000
      targetPort: 6379
      nodePort: 30003
